"""add image key columns

Revision ID: 247cbd61a3ad
Revises: 91afb379d785
Create Date: 2026-08-07 17:22:23.975853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247cbd61a3ad'
down_revision: Union[str, Sequence[str], None] = '91afb379d785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_reference_images', sa.Column('object_key', sa.String(length=512), nullable=True))
    op.add_column('materials', sa.Column('image_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'image_key')
    op.drop_column('design_reference_images', 'object_key')
    # ### end Alembic commands ###
