"""drop legacy leftovers

Revision ID: 91afb379d785
Revises: 94f07976cdfc
Create Date: 2026-08-07 17:05:44.440803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91afb379d785'
down_revision: Union[str, Sequence[str], None] = '94f07976cdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 这些遗留对象只存在于旧版 create_all 建出的数据库里；全新安装的基线
    # schema 不会创建它们，因此按存在性幂等删除，避免在空库上失败。
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('chat_user_messages'):
        op.drop_table('chat_user_messages')

    existing_columns = {
        column['name']
        for column in inspector.get_columns('chat_session_contexts')
    }
    for column_name in (
        'model3d_url',
        'model3d_walls',
        'model3d_revision',
        'model3d_error',
        'material_analysis',
        'model3d_status',
    ):
        if column_name in existing_columns:
            op.drop_column('chat_session_contexts', column_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session_contexts', sa.Column('model3d_status', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('material_analysis', mysql.JSON(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_error', mysql.TEXT(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_revision', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_walls', mysql.JSON(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_url', mysql.VARCHAR(length=512), nullable=True))
    op.create_table('chat_user_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('has_image', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_user_messages_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
