"""drop legacy leftovers

Revision ID: 91afb379d785
Revises: 94f07976cdfc
Create Date: 2026-08-07 17:05:44.440803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91afb379d785'
down_revision: Union[str, Sequence[str], None] = '94f07976cdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 整表删除会自动带走索引，无需单独 drop_index；
    # 实际表只有 PRIMARY 与 ix_chat_user_messages_user_id，另两个索引 autogenerate 误报
    op.drop_table('chat_user_messages')
    op.drop_column('chat_session_contexts', 'model3d_url')
    op.drop_column('chat_session_contexts', 'model3d_walls')
    op.drop_column('chat_session_contexts', 'model3d_revision')
    op.drop_column('chat_session_contexts', 'model3d_error')
    op.drop_column('chat_session_contexts', 'material_analysis')
    op.drop_column('chat_session_contexts', 'model3d_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session_contexts', sa.Column('model3d_status', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('material_analysis', mysql.JSON(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_error', mysql.TEXT(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_revision', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_walls', mysql.JSON(), nullable=True))
    op.add_column('chat_session_contexts', sa.Column('model3d_url', mysql.VARCHAR(length=512), nullable=True))
    op.create_table('chat_user_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('has_image', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_user_messages_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
