"""baseline schema

Revision ID: 94f07976cdfc
Revises: 
Create Date: 2026-08-07 17:00:23.140819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94f07976cdfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_contexts',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('reference_image_data_url', mysql.LONGTEXT(), nullable=True),
    sa.Column('reference_image_request', sa.Text(), nullable=True),
    sa.Column('generated_image_url', sa.String(length=512), nullable=True),
    sa.Column('generation_request', sa.Text(), nullable=True),
    sa.Column('selected_style_id', sa.String(length=64), nullable=True),
    sa.Column('context_revision', sa.Integer(), nullable=False),
    sa.Column('effect_revision', sa.Integer(), nullable=True),
    sa.Column('assets_expired_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('design_reference_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('data_url', mysql.LONGTEXT(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('material_name', sa.String(length=100), nullable=True),
    sa.Column('usages', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_reference_images_kind'), 'design_reference_images', ['kind'], unique=False)
    op.create_index(op.f('ix_design_reference_images_session_id'), 'design_reference_images', ['session_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('spec', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('cat', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_material'), 'materials', ['material'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('title_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_session_id', name='uq_chat_conversation_user_session')
    )
    op.create_index(op.f('ix_chat_conversations_client_session_id'), 'chat_conversations', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_session_id'), 'chat_conversations', ['session_id'], unique=True)
    op.create_index(op.f('ix_chat_conversations_updated_at'), 'chat_conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('style_id', sa.String(length=64), nullable=True),
    sa.Column('generated_image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_chat_message_sequence')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_generated_image_filename'), 'chat_messages', ['generated_image_filename'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_status'), 'chat_messages', ['status'], unique=False)
    op.create_index(op.f('ix_chat_messages_turn_id'), 'chat_messages', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_turn_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_status'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_generated_image_filename'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_updated_at'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_session_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_client_session_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_materials_material'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_design_reference_images_session_id'), table_name='design_reference_images')
    op.drop_index(op.f('ix_design_reference_images_kind'), table_name='design_reference_images')
    op.drop_table('design_reference_images')
    op.drop_table('chat_session_contexts')
    # ### end Alembic commands ###
