"""drop legacy image columns

Revision ID: ec176e80cea0
Revises: 247cbd61a3ad
Create Date: 2026-08-07 17:25:35.763599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec176e80cea0'
down_revision: Union[str, Sequence[str], None] = '247cbd61a3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session_contexts', 'reference_image_data_url')
    op.drop_column('design_reference_images', 'data_url')
    op.drop_column('materials', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('img', mysql.LONGTEXT(), nullable=False))
    op.add_column('design_reference_images', sa.Column('data_url', mysql.LONGTEXT(), nullable=False))
    op.add_column('chat_session_contexts', sa.Column('reference_image_data_url', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###
